# Generated by Django 2.2 on 2019-04-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20190412_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persoon',
            name='picture',
            field=models.TextField(blank=True, null=True, verbose_name='Foto'),
        ),
    ]
