# Generated by Django 2.2 on 2019-04-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_auto_20190414_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persoon',
            name='latest',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
