# Generated by Django 2.2.7 on 2019-11-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0014_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='performed_by',
            field=models.CharField(default='', max_length=255),
        ),
    ]
