# Generated by Django 3.2.12 on 2022-04-10 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0017_persoon_idp_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persoon',
            name='day_friday',
        ),
        migrations.RemoveField(
            model_name='persoon',
            name='day_saturday',
        ),
    ]
