# Generated by Django 4.0.6 on 2022-07-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0018_auto_20220410_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persoon',
            name='absent',
            field=models.BooleanField(default=False),
        ),
    ]
