version: '3'
services:
  corvee:
    container_name: corvee
    image: djoamersfoort/corvee:latest
    ports:
      - 8182:80
    volumes:
      - ./corvee/settings.py:/srv/corvee/corvee/settings.py:ro
    restart: always
    networks:
      - corvee

networks:
  corvee:
