# Generated by Django 2.2 on 2019-04-14 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_persoon_absent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persoon',
            options={'verbose_name_plural': 'Personen'},
        ),
    ]
