# Generated by Django 2.2.7 on 2019-11-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0013_persoon_marked_for_deletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(blank=True, default=None, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=20)),
            ],
        ),
    ]
