# Generated by Django 3.2.7 on 2021-09-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0016_lastsync'),
    ]

    operations = [
        migrations.AddField(
            model_name='persoon',
            name='idp_user_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
